[pyprland]
plugins = ["scratchpads"]

[scratchpads.term]
command = "DRI_PRIME=1002:1638 kitty --class kitty-dropterm"
animation = "fromTop"
position = "12% 50px"
size = "75% 60%"
max_size = "75% 80%"
